import '../../../../globals.css'
import Layout from '@/app/components/Layout/Layout'
import nacelleClient from '@/app/services/nacelleClient'
import { resolveSiteData } from '@/app/utils/resolvers/resolveSiteData'
import { SITE_QUERY } from '@/app/queries/site'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const data = await nacelleClient
    .query({ query: SITE_QUERY })
    .then(({ data }) => {
      return resolveSiteData({ client: nacelleClient, site: data });
    });
  const { space, products, ...rest } = data;

  return (
    <html lang="en">
      <body>
        <Layout components={rest}>
          {children}
        </Layout>
      </body>
    </html>
  )
}
